### ISSUE TITLE
There are no items in the Resources tab

### ISSUE THREAD

**Issue by ImGr0k** [Jako/modDevTools#2]
After updating to Modx 3.0 there is nothing to show on the resources tab. Has anyone experienced this, is this a known issue?

**Comment by Jako** [comment]
That looks like a bug. The count is set right but the list not.

**Comment by ImGr0k** [comment]
So what should I do?

**Comment by Jako** [comment]
This is fixed with 1.3.5. I am fixing that in my spare time, so please don't count on a quick reaction.

If you are confident with my work, there is a donate button on the right.

**Comment by AntonFix** [comment]
Hello,
I have same problem on MODX Revolution 3.0.4, package moddevtools-1.3.8-pl
![chrome_Wxg5Hrc9n1](https://github.com/Jako/modDevTools/assets/2990135/5a1844d0-bec5-42a4-9474-2531420d7514)

How to solve it?

**Comment by Jako** [comment]
Thats a different issue. Or at least your screenshot does not show the issue.

Can you open a new one and describe what does not work?
