### ISSUE TITLE
Show/Revert link to template in resource manager page

### ISSUE THREAD

**Issue by dimasites** [Jako/modDevTools#3]
hi @Jako and thanks for update extra!

In old 1.2.1-pl version i used very usefull link near template name in resource edit manager page.
But **in new version** 1.3.5-pl this link is gone! :) See screenshots:
![2023-03-06_00-12-13](https://user-images.githubusercontent.com/5102558/222986720-c81cd487-0161-40f3-9b77-0ec5540ae85a.png)

How i can revert this link without rollback to old moddevtools version, or may be it is bug and it must be there?

I use latest MODX2 2.8.4-pl in all cases

**Comment by Jako** [comment]
Fixed with 1.3.6
