### ISSUE TITLE
ModDevTools lists all Resources as unpublished

### ISSUE THREAD

**Issue by roydegler** [Jako/modDevTools#5]
All resources listed are shown as unpublished when viewing the resources tab.  However all resources are actually published. 

Environment:
MODX 3.0.4 on MODXCloud servers
Site was upgraded to MODX 3.x from MODX 2.8.x
 
<img width="795" alt="moddevtools-unpublished" src="https://github.com/Jako/modDevTools/assets/6529000/ee095360-94a8-48fb-b6cb-06d31b3207b9">

**Comment by Jako** [comment]
This is fixed with ModDevTools 1.3.7.
