### ISSUE TITLE
The Resources tab is hidden

### ISSUE THREAD

**Issue by AntonFix** [Jako/modDevTools#6]
Hello,
I use MODX Revolution 3.0.4, package moddevtools-1.3.8-pl

The Resources tab is hidden but other tabs are visible.
I've refreshed all items in the tab Refresh. It's happend without errors for all resources.

```
Console running...
Regenerated links to resource: Home (1)
Regenerated links to resource: Thema's (2)
Regenerated links to resource: Aanbod (3)
...
```

![chrome_Wxg5Hrc9n1](https://github.com/Jako/modDevTools/assets/2990135/5a1844d0-bec5-42a4-9474-2531420d7514)

How to solve it?

**Comment by Jako** [comment]
There is no resources tab in the custom manager page. It is only shown on the edit chunk/snippet/template page.

**Comment by AntonFix** [comment]
Yes, you are right! Sorry. Pls, close the ticket.
